openapi: 3.0.0
info:
  version: 1.0.0
  title: JWT Example
  description: Optional multiline or single-line description
host: http://localhost:5000
basepath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
